---
- import_tasks: setup.yml

- import_tasks: config.yml
  when: filebeat_create_config

- name: Ensure Filebeat is started and enabled at boot.
  systemd:
    name: filebeat
    state: started
    enabled: "{{ filebeat_enabled_on_boot }}"
    daemon_reload: yes
